from .event import Event
from .page_created import PageCreated
from .page_deleted import PageDeleted
from .page_moved import PageMoved
from .page_protection_modified import PageProtectionModified
from .page_restored import PageRestored
from .revisions_deleted import RevisionsDeleted
#from .revision_restored import RevisionRestored
from .revision_saved import RevisionSaved
from .user_blocked import UserBlocked
from .user_groups_modified import UserGroupsModified
from .user_registered import UserRegistered
from .user_renamed import UserRenamed
from .user_unblocked import UserUnblocked
